version: '3.7'
networks:
  template_network:
    driver: bridge
services:
  template_react_server:
    build: ./client
    restart: always
    stdin_open: true
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    links:
      - template_node_express_server
    networks:
      - template_network
  template_node_express_server:
    build: ./server
    restart: always
    environment:
      WAIT_HOSTS: template_mysql:3306
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - template_mysql
    networks:
      - template_network
  template_mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: template_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'testdb'
      MYSQL_HOST: 'mysql'
    volumes:
      - ./data-node:/data/db
    networks:
      - template_network
    ports:
      - 3306:3306
  template_nginx:
    image: nginx
    container_name: template_nginx
    networks:
      - template_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - template_node_express_server
      - template_react_server
